title: Micah Dotzert's Personal Blog
author: Micah Dotzert
email: pdotzert7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Micah Dotzert, a software developer located near Elmira, Ontario,'s personal blog.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  md-hexdrive # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
